### ISSUE TITLE
Cannot read property 'StatusCode' of null

### ISSUE THREAD

**Issue by smazurov** [VictorBjelkholm/autochecker#12]
Tried running `autochecker` on an older node project to see if tests pass on newer versions. Ran into this problem:

```
autochecker Running tests in 32 different NodeJS versions
0.10.41	- building image
0.10.42	- building image
0.10.43	- building image
0.10.44	- running container
0.12.9	- building image
0.12.10	- building image
0.12.11	- building image
0.12.12	- building image

/usr/local/lib/node_modules/autochecker/index.js:122
      var to_resolve = {success: data.StatusCode === 0}
                                     ^

TypeError: Cannot read property 'StatusCode' of null
    at /usr/local/lib/node_modules/autochecker/index.js:122:38
    at handler (/usr/local/lib/node_modules/autochecker/node_modules/dockerode/lib/docker.js:541:21)
    at /usr/local/lib/node_modules/autochecker/node_modules/dockerode/lib/docker.js:37:21
    at /usr/local/lib/node_modules/autochecker/node_modules/docker-modem/lib/modem.js:235:7
    at getCause (/usr/local/lib/node_modules/autochecker/node_modules/docker-modem/lib/modem.js:257:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/autochecker/node_modules/docker-modem/lib/modem.js:228:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/autochecker/node_modules/docker-modem/lib/modem.js:204:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
```

```
$ docker version 
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.6
 Git commit:   20f81dd
 Built:        Sat Mar 12 04:07:44 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64

**Comment by VictorBjelkholm** [comment]
Try running just one version to see the more verbose output, would help to fix it

**Comment by smazurov** [comment]
I see, I believe my issue was that docker vm ran out of space on its disk and was failing to start. I leave this open as I'm assuming you would want to handle this case more gracefully.

**Comment by VictorBjelkholm** [comment]
Should be easier to see now. Thanks a lot for reporting this 👍

**Comment by smazurov** [comment]
Thanks!
